### PR TITLE
generate:database -d does not clean the Rules table

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This should fail, in certain situations.

**Comment by giorgiosironi** [comment]
Still the test does not reproduce the problem, which I can manually...

**Comment by stephenwf** [comment]
I'm not sure what caused it, if there was a change to the schema, it might have invalidated the drop query.. but it seems unlikely

**Comment by giorgiosironi** [comment]
Sample steps to reproduce: in a MySQL console,
```
DROP TABLE `References`
DROP TABLE Rules
```
then run:
```
bin/console generate:database --env=dev
```
This fails for me:
```
[2017-03-03 11:42:48] recommendations-api.ERROR: An exception occurred while executing 'ALTER TABLE `References` ADD CONSTRAINT FK_D0432E4C9FB98B93 FOREIGN KEY (on_id) REFERENCES Rules (rule_id) ON UPDATE CASCADE':  SQLSTATE[HY000]: General error: 1005 Can't create table 'recommendations.#sql-468_39' (errno: 150) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'ALTER TABLE `References` ADD CONSTRAINT FK_D0432E4C9FB98B93 FOREIGN KEY (on_id) REFERENCES Rules (rule_id) ON UPDATE CASCADE':\n\nSQLSTATE[HY000]: General error: 1005 Can't create table 'recommendations.#sql-468_39' (errno: 150) at /srv/recommendations/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1005 Can't create table 'recommendations.#sql-468_39' (errno: 150) at /srv/recommendations/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:59, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1005 Can't create table 'recommendations.#sql-468_39' (errno: 150) at /srv/recommendations/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57)"} 
  [Doctrine\DBAL\Exception\DriverException]                                         
  An exception occurred while executing 'ALTER TABLE `References` ADD CONSTRAINT F  
  K_D0432E4C9FB98B93 FOREIGN KEY (on_id) REFERENCES Rules (rule_id) ON UPDATE CASC  
  ADE':                                                                             
  SQLSTATE[HY000]: General error: 1005 Can't create table 'recommendations.#sql-46  
  8_39' (errno: 150)                                                                
  [Doctrine\DBAL\Driver\PDOException]                                               
  SQLSTATE[HY000]: General error: 1005 Can't create table 'recommendations.#sql-46  
  8_39' (errno: 150)                                                                
  [PDOException]                                                                    
  SQLSTATE[HY000]: General error: 1005 Can't create table 'recommendations.#sql-46  
  8_39' (errno: 150)                                                                                                   
generate:database [-d|--drop]
```
Other problems down the line but this is the simplest to reproduce at the moment.

**Comment by stephenwf** [comment]
Closed, see #55

**Pull request closed without merging**
