### PR TITLE
Use Article VoR v3

### PR DESCRIPTION
**Pull request by thewilkybarkid**
https://github.com/elifesciences/issues/issues/4781

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Know of any changes that could be causing the failure @giorgiosironi?

**Comment by giorgiosironi** [comment]
Seems to be copying test artifacts out of the container, but there aren't any defined in the Jenkinsfile.

**Comment by giorgiosironi** [comment]
Ah, the default is `build/*.xml`, would catch `build/phpunit.xml` but the whole folder seems to be missing.

**Comment by giorgiosironi** [comment]
In the previous step I see:
```
[2019-08-22T12:43:03.710Z] .....................                                             21 / 21 (100%)PHP Warning:  file_put_contents(/srv/recommendations/.phpunit.result.cache): failed to open stream: Permission denied in /srv/recommendations/vendor/phpunit/phpunit/src/Runner/DefaultTestResultCache.php on line 107
```
so possibly a similar permission problem.

**Comment by giorgiosironi** [comment]
Locally, PHPUnit shows the same `file_put_contents(/srv/recommendations/.phpunit.result.cache)` problem, but it does write to `build/` successfully.

**Comment by giorgiosironi** [comment]
Also locally, seems `build/` on the host is being created by docker as the target of `docker cp`, but doesn't happen on Jenkins.

**Comment by giorgiosironi** [comment]
Executed on a Jenkins node being turned off, so have to reexecute to watch.

**Comment by giorgiosironi** [comment]
Jenkins node `docker version` is 1 year newer, if it makes any difference. Adding explicit creation of the folder.

**Pull request merged**
