### PR TITLE
ELPP-2570 Update images for IIIF

### PR DESCRIPTION
**Pull request by thewilkybarkid**

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
I think the failure here is that the cache isn't being cleared. /cc @giorgiosironi @stephenwf

**Comment by giorgiosironi** [comment]
I remember cache invalidation here was complex because it's done on updates from bus and kept around forever, this to avoid reaching out to all other services when composing API responses. We could do it on deploy if that makes it easier, sacrificing a bit of performance? With a 1 second target response time I don't know if it's feasible.

**Comment by giorgiosironi** [comment]
We can also do it before tests, but that may not solve the same problem happening in production.

**Comment by thewilkybarkid** [comment]
The caching I'm referring to is the annotation cache, so it's important that it's cleared on a code change (`var/cache/annotations` and `var/cache/metadata`).

**Comment by giorgiosironi** [comment]
I inserted a blunt clearing which made the build green, there may be a better way.

**Comment by thewilkybarkid** [comment]
Should we merge? Don't know if it requires a reindex.

**Comment by stephenwf** [comment]
won't require a reindex, cache should be cleared on deploy for the metadata 👍

**Pull request merged**
