### PR TITLE
Added various SQL queries used during development

### PR DESCRIPTION
**Pull request by stephenwf**
@giorgiosironi 

I've added these to their own files, let me know what assertions we can/should be making using these

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Any count that you can make from this ones that should always be a fixed number after importing the api-dummy? That can be added to the end of `bin/ci-import`.

**Comment by stephenwf** [comment]
I've added in a `query-count` command so..

```
$ ./bin/count-query latest-articles --env=local
```

Will return the number of articles

**Comment by giorgiosironi** [comment]
Useful code. Why not in the `bin/console` (do we have `bin/console`?)?

**Comment by stephenwf** [comment]
Oh we do, ill move it to there instead!

**Pull request merged**
