### PR TITLE
ELPP-2044 Added more transactions for recommendations

### PR DESCRIPTION
**Pull request by stephenwf**
@giorgiosironi

This now adds monitoring class to all of the processes currently set up for recommendations. The last thing to add it runtime transactions. Do you think we should record generating the results (based on the rules) in NewRelic?

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Is generating the results something done inside an HTTP request? If so, with Silex that should be automatically recorded.
However, I don't see recommendations--prod on New Relic APM yet, investigating.

**Comment by giorgiosironi** [comment]
Here it is https://rpm.newrelic.com/accounts/1451451/applications/34503778
And at https://rpm.newrelic.com/accounts/1451451/applications/34503778/transactions web transactions should be listed automatically

**Comment by stephenwf** [comment]
So there is no need to break down each request by rules themselves?

**Comment by giorgiosironi** [comment]
Ah, splitting HTTP requests in multiple transactions; that may be confusing, I would start with the default.

**Pull request merged**
